---
- name: Deploy NSX OVA
  hosts: jumphost
  gather_facts: False
  vars_files:
    - answerfile-deployLab.yml
  roles:
    - role: deploy-nsx-ova
  tags: nsx_ova

- name: Base NSX Deployment (Install)
  hosts: jumphost
  gather_facts: False
  vars_files:
    - answerfile-deployLab.yml
  roles:
    - role: base-config-nsx
  tags: nsx_install


