---
- hosts: localhost
  connection: local
  gather_facts: False
  vars_files:
     - answerfile_TPM_Lab_deploy.yml
  tasks:
  - name: Apply NSX License
    vcenter_nsx_license:
      vcenter: "{{ vcHostname }}"
      vcenter_user: "{{ vcUser }}"
      vcenter_passwd: "{{ vcPassword }}"
      license_key: "L029P-JLL8K-28089-0UCK6-1TCH1"
      # Note: The above license is an old time bombed license. Don't apply it to production!
    register: nsxlic
    tags: nsx_license

  - debug: msg="{{ nsxlic }}"